add PriceWithDiscount, amount and NumberPrice
Adobe-for-Alex/telegram-bot pull request #30
Opened 2024-11-03 17:12 UTC by gerushenka

Fixes:
#22 #23

2024-11-04 11:01 UTC, Chamber6821 commented
@gerushenka к сожалению то формат в котором ты упомянул issues не распознаются github'ом, напиши пожалуйста для каждого issue в отдельной строке по примеру как в README

2024-11-04 21:33 UTC, Chamber6821 requested changes

2024-11-04 22:18 UTC, Chamber6821 requested changes

2024-11-04 22:21 UTC, gerushenka commented on src/price/NumberPrice.test.ts
> +  it('should return a floating point price', async () => {
затуп споймал, поменял везде на `must`

2024-11-04 22:28 UTC, Chamber6821 commented
Ты походу GPT используешь. Следи пожалуйста, что бы он код в одном стиле писал. Например в `src/price/NumberPrice.test.ts` использование `expect` отличается от всех других мест использования

2024-11-04 22:56 UTC, Chamber6821 commented
Асинхронный `expect` не всегда нужен, поэтому лучше просто сделай как было с `await` внутри `expect`

2024-11-04 23:08 UTC, Chamber6821 commented
В теле теста можно не писать async/await если там всего 1 await:

```ts
it('test', () =>
  expect(new Price().amout()).resolves.toBe(42)
)
```

2024-11-04 23:12 UTC, Chamber6821 commented
Можно вообще без async/await. Т.к. `expect` возвращет `Promise`, мы можем не ждать его, а просто вернуть наружу

2024-11-04 23:12 UTC, Chamber6821 commented
Или ты думаешь async/await стоит явно написать?

2024-11-05 11:55 UTC, Chamber6821 requested changes

2024-11-05 11:55 UTC, Chamber6821 commented on src/price/NumberPrice.test.ts
Убери `;`

2024-11-05 11:55 UTC, Chamber6821 commented on src/price/NumberPrice.ts
Убери `;`

2024-11-05 11:55 UTC, Chamber6821 commented on src/price/PriceWithDiscount.test.ts
Убери `;`

2024-11-05 11:55 UTC, Chamber6821 commented on src/price/PriceWithDiscount.ts
Убери `;`

2024-11-05 17:03 UTC, Chamber6821 requested changes

2024-11-05 17:03 UTC, Chamber6821 commented on src/price/PriceWithDiscount.test.ts
> +)
Отступ

2024-11-05 17:03 UTC, Chamber6821 commented on src/price/NumberPrice.ts
> +
Удали пустую строку

2024-11-05 17:03 UTC, Chamber6821 commented on src/price/PriceWithDiscount.ts
> +
Удали пустую строку

2024-11-05 19:05 UTC, Chamber6821 approved these changes

2024-11-05 19:06 UTC, merged