add file, chained, image and text messages
Adobe-for-Alex/telegram-bot pull request #31
Opened 2024-11-03 17:12 UTC by gerushenka

Fixes 
#17 #18 #19 #20

2024-11-04 11:02 UTC, Chamber6821 commented
@gerushenka к сожалению то формат в котором ты упомянул issues не распознаются github'ом, напиши пожалуйста для каждого issue в отдельной строке по примеру как в README

2024-11-04 11:31 UTC, Chamber6821 requested changes

2024-11-04 11:31 UTC, Chamber6821 commented on src/message/ChainedMessage.test.ts
> +    };
Вместо написания моков (тесты построенные на моках либо ничего не тестируют, либо хрупкие и сложные одновременно), лучше напиши фейковую реализацию для Chat содержимое которого ты сможешь проверить. Например эта реализация может конкатенировать весь пришедший текст, файлы и картинки в строку. Как я это вижу:
```ts
let chatContent = ''
const chat = new Chat.Fake(part => chatContent += `\n\n${part}`)
...
expected(chatContent).toMatch(/First message\s+SecondMessage/)
```

2024-11-04 11:31 UTC, Chamber6821 commented on src/message/ChainedMessage.test.ts
> +    const mockFile = {} as File;
Из-за такого костыля, этот тест станет падать со странными ошибками, если реализация изменится. Лучше написать заглушку, которая всегда возвращается один и тот же заданный URL

2024-11-04 11:31 UTC, Chamber6821 commented on src/message/FileMessage.test.ts
Тоже самое как и для `ChainedMessage.test.ts`

2024-11-04 11:31 UTC, Chamber6821 commented on src/message/ImageMessage.test.ts
Тоже самое как и для `ChainedMessage.test.ts`

2024-11-04 11:31 UTC, Chamber6821 commented on src/message/TextMessage.test.ts
Тоже самое как и для `ChainedMessage.test.ts`

2024-11-04 11:31 UTC, Chamber6821 commented on src/message/ChainedMessage.test.ts
> +    expect(mockChat.sendFile).toHaveBeenCalledTimes(1);
Использование моков в этом месте не гарантирует порядок отправки, а так же тест сломается, если сообщение захочет отправлять какой-нибудь префикс или завернуть файл в какую-нибудь обертку, т.е. тест хрупкий и не тестирует то, что важно. Поэтому не стоит использовать моки в принципе, предпочтительнее написание специальных реализаций интерфейсов для тестов

2024-11-04 15:19 UTC, Chamber6821 commented
Зачем ты закрыл PR?

2024-11-04 21:35 UTC, Chamber6821 commented on src/chat/FakeChat.ts
> +}
Лучше помести его прям внутри интерфейса, это удобный шаблон для тестирования

2024-11-04 21:36 UTC, Chamber6821 commented on src/message/ChainedMessage.test.ts
> +  it("должен отправить несколько сообщений последовательно через FakeChat", async () => {
Переведи на английский и без упоминания FakeChat

2024-11-04 21:37 UTC, Chamber6821 commented on src/message/ChainedMessage.ts
> +  }
В TS есть сокращение для такого кода:
```ts
contstructor(
  private readonly messages: Message[]
) {}
```
думаю стоит пожертвовать rest оператором взамен на более краткий синтаксис без дублирования кода

2024-11-04 21:41 UTC, Chamber6821 commented on src/message/FileMessage.test.ts
> +  it("должен отправить файл через FakeChat", async () => {
Переведи на русский

2024-11-04 21:41 UTC, Chamber6821 commented on src/message/ImageMessage.test.ts
> +  it("должен отправить изображение через FakeChat", async () => {
Переведи на русский

2024-11-04 21:41 UTC, Chamber6821 commented on src/message/FileMessage.ts
> +  }
Есть скоращение

2024-11-04 21:41 UTC, Chamber6821 commented on src/message/ImageMessage.ts
> +  }
Есть сокращение

2024-11-04 21:41 UTC, Chamber6821 commented on src/message/TextMessage.test.ts
> +  it("должен отправить текстовое сообщение через FakeChat", async () => {
Переведи на русский

2024-11-04 21:42 UTC, Chamber6821 commented on src/message/TextMessage.ts
> +  }
Есть сокращение

2024-11-04 21:42 UTC, Chamber6821 commented on src/chat/FakeChat.ts
> +    return Promise.resolve();
Вместо этого, можно просто объявить метод `async` и компилятор все сделает за тебя

2024-11-04 21:45 UTC, Chamber6821 commented on src/message/ChainedMessage.test.ts
> +    const mockFile = {} as File;
@gerushenka

2024-11-04 22:42 UTC, Chamber6821 commented
В другом PR ты не используешь асинхронный `expect` да и в принципе не всегда нужен именно он, поэтому лучше просто сделай как было с `await` внутри `expect`

2024-11-04 22:53 UTC, Chamber6821 requested changes

2024-11-04 22:53 UTC, Chamber6821 commented on src/chat/Chat.ts
> +    this.chatContent += `\n\nImage: [file: ${image.toString()}]`;
У файла есть URL

2024-11-04 22:53 UTC, Chamber6821 commented on src/chat/Chat.ts
> +    this.chatContent += `\n\nFile: [file: ${file.toString()}]`;
У файла есть URL

2024-11-04 23:05 UTC, Chamber6821 commented
Я дурак, перепиши обратно все `expect` на `resolves` и `rejects`. К тому же можно убрать в теле теста фигурные скобочки и `await`:
```ts
it('', () => expect(promise).resolves.toBe(42))
```

2024-11-04 23:26 UTC, Chamber6821 commented
Теперь запиши каждый тест в 2 выражения: объявление фейкового чата, создание сообщения и его отправка, проверка содержимого чата

2024-11-05 11:54 UTC, Chamber6821 requested changes

2024-11-05 11:54 UTC, Chamber6821 commented on src/chat/Chat.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/file/File.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/ChainedMessage.test.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/ChainedMessage.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/FileMessage.test.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/FileMessage.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/FileMessage.ts
> +) {}
Че с форматированием?

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/ImageMessage.test.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/ImageMessage.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/ImageMessage.ts
> +) {}
Че с форматированием?

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/TextMessage.test.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/TextMessage.ts
Убери `;`

2024-11-05 11:54 UTC, Chamber6821 commented on src/message/TextMessage.ts
> +) {}
Че с форматированием?

2024-11-05 16:58 UTC, Chamber6821 requested changes

2024-11-05 16:58 UTC, Chamber6821 commented on src/message/ImageMessage.ts
>  ) {}
Добавь отступ

2024-11-05 16:58 UTC, Chamber6821 commented on src/message/TextMessage.ts
>  ) {}
Добавь отступ

2024-11-05 16:59 UTC, gerushenka commented on src/message/ImageMessage.ts
>  ) {}
а какая проблема тогда  с форматированием, не понимаю

2024-11-05 16:59 UTC, Chamber6821 commented
@gerushenka не все `;` убрал, смотри открытые треды

2024-11-05 17:01 UTC, Chamber6821 commented on src/message/ImageMessage.ts
>  ) {}
у тебя написано
```ts
  ctor(
    ...
) {}
```
а должно быть
```ts
  ctor(
    ...
  ) {}
```

2024-11-05 17:05 UTC, Chamber6821 requested changes
И верни обратно все `;` в импортах, это было лишнее изменение

2024-11-05 17:05 UTC, Chamber6821 commented on src/chat/Chat.ts
> +}
Вот тут остались лишние `;`

2024-11-05 17:06 UTC, Chamber6821 commented on src/chat/Chat.ts
> +}
Неужели так сложно посмотреть к какому файлу относится исходный комментарий?

2024-11-05 17:29 UTC, Chamber6821 approved these changes

2024-11-05 17:29 UTC, merged