Add interfaces and types
Adobe-for-Alex/telegram-bot pull request #8
Opened 2024-10-28 18:17 UTC by gerushenka

Fixes #7

2024-10-29 15:31 UTC, Chamber6821 requested changes

2024-10-29 15:32 UTC, Chamber6821 commented
Покажи пример, как ты хочешь соединять эти абстракции

[Вот](https://github.com/yegor256/takes?tab=readme-ov-file#exception-handling) что, я имею в виду

2024-10-30 13:24 UTC, Chamber6821 commented
Пример как это может выглядеть

https://github.com/Adobe-for-Alex/adobe-api/pull/5#issuecomment-2446095897

2024-10-30 13:46 UTC, Chamber6821 commented on src/types/types.ts
> +}
Новый вариант `Payment`
```ts
interface Payment {
  asMessage(): Promise<TelegramMessage>
}
```

2024-10-30 13:46 UTC, Chamber6821 commented on src/types/types.ts
> +}
Возможное использование `Payment`. Я опустил все async/await
```ts
const payment = new ScreenPayment( // ScreenPayment может под капотом обращаться к БД
  userName,
  context->image()
)
if (ardmins.anyNotBusy().requestPaymentVerification(payment)) === 'approved') {
  payment.extend(users.withId(userId).session())
}
```

2024-10-30 14:15 UTC, gerushenka commented
async function processPayment(userId: TelegramId) {
    const payment = new ScreenPayment(userName, context.image());
    const price = await payment.price();
    const amount = await price.amount(); 

    const admin = await admins.anyNotBusy();
    if (!admin) {
        throw new Error("нет доступных админов");
    }

    const verification = await admin.requestPaymentVerification(payment);
    if (verification === 'approved') { 
        const user = await users.withId(userId);
        if (user) {
            const session = await service.createSession(userId, period);
            await user.setSubscription(session);
        }
    } else {
        console.log("REJECT");
    }
}
получается  что оплата будет формироваться в price а amount будет итоговой суммой со скидкой

2024-10-30 14:45 UTC, Chamber6821 commented
Это то, что нужно, опиши пожалуйста больше сценариев. Например отправка сообщений пользователю и приветствие нового. Каждая реакция бота - это какой-то объект

2024-10-30 17:06 UTC, Chamber6821 commented
@gerushenka пиши код, пожалуйста, в таких кавычках:
\`\`\`ts
code
\`\`\`
так он будет красиво подсвечиваться. ts - это TypeScript. Github поддерживает многие популярные языки

2024-10-30 17:18 UTC, Chamber6821 commented
Это то, что я хотел (хотя и не в точности правильно в моем понимании)! Общая рекомендация: лучше не пладить кучу констант, а стараться писать все в одно выражение. Если становится сложно ориентироваться в этом выражении, это сигнал того, что стоит переформулировать его или разбить на отдельные самостоятельные части. Такой подход позволяет избегать портянок кода практически везде

2024-10-30 17:33 UTC, Chamber6821 commented
По поводу [этого](https://github.com/Adobe-for-Alex/telegram-bot/pull/8#issuecomment-2447309130) сценария

Декомпозиция - в общем случае плохо, хотя и является самым простым с ходу решением
Например, лучше вместо `payment.price()` сделать так, что бы `price` передавался в конструкторе и был инкапсулирован внутри `payment`. Пример:

```ts
const price = new DiscountPrice(new DollarPrice(42), 10)
user.sendMessage(new StringMessage(`Новая подписка обойдется вам в ${price.asString()}`))
const answer = user.answer()
admin.approve(new GeneralPayment(
  userName,
  price
  answer.file()
)).extend(user.session())
```

2024-10-30 17:47 UTC, Chamber6821 commented
@gerushenka тебе понятна последняя пара рекомендация? Если да, то перепиши пожалуйста сценарии с учетом их. Еще, думаю лучше будет, если с пользователем ты будешь общаться через интерфейс `User`, что-то вроде:
- `user.send(message)`
- `message = user.answer()`
Причем пускай `message` будет тоже интерфейсом, что бы мы могли прикреплять к сообщению картинки и файлы через декораторы: `new MessageWithImage(new TextMessage('Привет, землянин!'), new Image('/assets/hello-cat.png'))`

2024-10-30 17:55 UTC, gerushenka commented
> @gerushenka тебе понятна последняя пара рекомендация? Если да, то перепиши пожалуйста сценарии с учетом их. Еще, думаю лучше будет, если с пользователем ты будешь общаться через интерфейс `User`, что-то вроде:
> 
> * `user.send(message)`
> * `message = user.answer()`
> 
> Причем пускай `message` будет тоже интерфейсом, что бы мы могли прикреплять к сообщению картинки и файлы через декораторы: `new MessageWithImage(new TextMessage('Привет, землянин!'), new Image('/assets/hello-cat.png'))`

2024-10-30 17:55 UTC, gerushenka commented
> @gerushenka тебе понятна последняя пара рекомендация? Если да, то перепиши пожалуйста сценарии с учетом их. Еще, думаю лучше будет, если с пользователем ты будешь общаться через интерфейс `User`, что-то вроде:
> 
> * `user.send(message)`
> * `message = user.answer()`
> 
> Причем пускай `message` будет тоже интерфейсом, что бы мы могли прикреплять к сообщению картинки и файлы через декораторы: `new MessageWithImage(new TextMessage('Привет, землянин!'), new Image('/assets/hello-cat.png'))`

Понял, сейчас сделаю

2024-10-30 18:26 UTC, gerushenka commented
# Оплата
```ts
async function processPayment(userId: TelegramId) {
    const price = new DiscountPrice(new DollarPrice(42), 10);
    user.send(new StringMessage(`Новая подписка обойдется вам в ${price.asString()}`))
    const admin = await admins.anyNotBusy();

    admin.approve(
    userName
    new GeneralPayment(
    price
    answer.file()
    )
  ).extend(user.session())
    const user = await users.withId(userId);

    if (verification === 'approved' && user) {
        const session = await service.createSession(userId, period);
        await user.setSubscription(session);
        await user.send(new TextMessage(`Оплата одобрена. Подписка активирована до ${session.endDate()}.`));
    } else {
        await user.send(new TextMessage("Извините, ваша оплата отклонена."));
    }
}
```
# приветствие пользователя

регестрируем пользователя --> получаем имя и приветствуем --> предлагаем оформить подписку  если её нет
```ts
async function newUser(userId: TelegramId, chatId: ChatId, nickname: TelegramNickname) {
    const users = await service.users();
    let user = await users.withId(userId);
    if (!user) {
        user = await users.register(userId, chatId);
    }

    const userName = await user.name();
    await user.send( new TextMessage(`Привет, ${userName}! Добро пожаловать в наш сервис.`));

    const currentSubscription = await user.subscription();

    if (!currentSubscription) {
        await user.send(new TextMessage("У вас пока нет активной подписки. Хотите оформить её сейчас?"));
    }
}

```
# напоминание о подписке

проверяем сколько дней до конца подписки и отправляем сообщение о скором истечении её
```ts

async function sendSubscriptionReminder(user: User): Promise<void> {
    const session = await user.subscription();
    if (!session) {
        return; 
    }
    const endDate = await session.endDate();
    const currentDate = new Date();
    const daysRemaining = Math.ceil((endDate.getTime() - currentDate.getTime()) / (1000 * 60 * 60 * 24));
    if (daysRemaining <= 3) {
        await user.send(new TextMessage(`Ваша подписка заканчивается через ${daysRemaining} дней.`));
    }
}

```

# окончание подписки 

вместо текста можно в целом использовать кнопки 
```ts
async function handleSubscriptionEnd(userId: TelegramId) {
    const user = await users.withId(userId);
    if (!user) return;

    const currentSession = await user.subscription();
    const hasExpired = !currentSession || new Date() > await currentSession.endDate();

    if (!hasExpired) {
        return;
    }

    await user.send(new TextMessage("Ваша подписка закончилась. Хотите продлить её, чтобы сохранить доступ?"));

    const wantsToRenew = await user.answer();
    if (wantsToRenew.asString().toLowerCase().includes("да")) {
        const period = 30;
        const session = await service.createSession(userId, period);
        await user.setSubscription(session);
        await user.send(new TextMessage(`Подписка успешно продлена и будет действовать до ${await session.endDate()}. Спасибо, что остаетесь с нами!`));
    } else {
        const discount = await price.discount();
        const discountedAmount = await price.discountedAmount();
        await user.send(new TextMessage(`Продлите подписку сейчас и получите скидку ${discount}%! Всего за ${discountedAmount} рублей. Хотите воспользоваться предложением?`));

        const response = await user.answer();
        if (response.asString().toLowerCase().includes("да")) {
            const session = await service.createSession(userId, 30);
            await user.setSubscription(session);

            await user.send(new TextMessage(`Ваша подписка активирована до ${await session.endDate()}.`));
        } else {
            await user.send(new TextMessage("Спасибо за использование нашего сервиса! Мы всегда рады вам."));
        }
    }
}
```

2024-10-30 19:25 UTC, Chamber6821 requested changes

2024-10-30 19:25 UTC, Chamber6821 commented on src/types/types.ts
> +}
Я понял, что нам не нужен `Service` для описания самого себя, поэтому удаляй

2024-10-30 19:25 UTC, Chamber6821 commented on src/types/types.ts
> +    requestPaymentVerification(payment: Payment): Promise<'approved' | 'rejected'>
Замени на `approve(payment: Payment): Promise<Payment>`

2024-10-30 19:28 UTC, Chamber6821 commented
После изменений, раскидай все интерфейсы по файлам по шаблону: `Payment` -> `src/payment/Payment.ts`. Это нужно для группировки реализаций интерфейсов по папкам

2024-10-30 20:22 UTC, Chamber6821 requested changes
+ взде отступ в 2 пробела. Я как-нибудь потом настрою автоматическую проверку кодстайла

2024-10-30 20:22 UTC, Chamber6821 commented on src/user/User.ts
> +    send(): Promise<void>;
Добавь аргумент `message: Message`

2024-10-30 20:22 UTC, Chamber6821 commented on src/user/User.ts
> +}
Нужен еще метод `answer(): Promise<Message>`, что бы получать от пользователя сообщения

2024-10-30 20:22 UTC, Chamber6821 commented on src/message/Message.ts
> +    asString(): Promise<string>;
Пущай у `Message` будет метод `send(context: Context): Promise<void>`. `Context` - это из `Telegraf`

2024-10-30 20:26 UTC, gerushenka commented on src/message/Message.ts
> +    asString(): Promise<string>;
если в Message будет send его удалить из User?

2024-10-30 20:35 UTC, Chamber6821 commented
В TS можно писать
```ts
export default interface A {}
```
вместо
```ts
interface A{}
export default A
```
Второй вариант менее предпочтителен из-за дублирования кода

2024-10-31 18:21 UTC, Chamber6821 requested changes

2024-10-31 18:21 UTC, Chamber6821 commented on src/message/Message.ts
> +  send(context: Context): Promise<void>;
Я почитал про `Context`, мы не во всех сценариях сможем его получить (например когда захотим уведомить пользователя). Поэтому стоит ввести дополнительную абстракцию `Chat` с методами для отправки разнообразного контента: текст, картинки, файлы (можно начать с этого)

2024-10-31 20:05 UTC, Chamber6821 requested changes

2024-10-31 20:05 UTC, Chamber6821 commented on src/message/Message.ts
> +}
Каждый интерфейс (пока у нас исключений не появилось) должен быть в своей папке и файле, как и остальные интерфейсы. Это структура проекта

2024-10-31 20:05 UTC, Chamber6821 commented on src/message/Message.ts
> +  sendFile(fileUrl: string): Promise<void>;
Сомневаюсь, что мы сможем работать с URL. Посмотри, что нужно отправлять в Telegraf, что бы отправить картинку и файл

2024-10-31 20:05 UTC, Chamber6821 commented on src/index.ts
Ревертни файл, пожалуйста

2024-10-31 21:35 UTC, Chamber6821 requested changes
Так же не должно быть `;`

2024-10-31 21:35 UTC, Chamber6821 commented on src/index.ts
Реверт - это значит вернуть в исходное состояние. В этом случае в то, в каком файл был до твоего PR

2024-10-31 21:35 UTC, Chamber6821 commented on src/file/File.ts
> +}
В интерфейсе не должны торчать поля. Это те места, которые не возможно (или очень сложно) кастомизировать в будущем. Поэтому оставь просто метод `url(): Promise<URL>`

2024-10-31 21:37 UTC, Chamber6821 commented on src/message/Message.ts
> +    asString(): Promise<string>;
Нет. User будет предоставлять Chat в который будет отправлен Message

2024-10-31 21:42 UTC, Chamber6821 requested changes

2024-10-31 21:42 UTC, Chamber6821 commented on package-lock.json
В проекте используется `pnpm`, а не `npm`. Удали этот файл

2024-10-31 21:42 UTC, Chamber6821 commented on src/aliases.ts
> +type TelegramNickname = string;
Ты не экспортировал эти алиасы, к ним нельзя получить доступ из других частей кода

2024-10-31 21:56 UTC, Chamber6821 requested changes

2024-10-31 21:56 UTC, Chamber6821 commented on src/chat/Chat.ts
> +  sendImage(image: File): Promise<void>; // Изменили тип на File
Удали комментарий

2024-10-31 21:56 UTC, Chamber6821 commented on src/message/Message.ts
> +  send(context: Chat): Promise<void>;
Переименуй на `sendTo`. Сори за такие частые мелкие изменения туда-сюда. Уже почти закончили

2024-10-31 21:56 UTC, Chamber6821 commented on src/users/Users.ts
> +  withId(id: TelegramId): Promise<User>;
Пользователь может быть не найден, поэтому `User` -> `User | undefined`

2024-10-31 22:15 UTC, Chamber6821 commented
Последние стилистические штрихи. Убери везде из объявления интерфейсов `;`, но при этом оставь в строчках с `import`. Так же перемести все `as*` методы в конец объявленя интерфейса.

В будущем будет автоматический линтер, который сделает эту часть работы за тебя и мне не надо будет писать об этом. Оставить `;` в строке `import` я сказал что бы было сейчас меньше гемороя, а стиль проекта выдерживался. Я так понял, что твой редактор (как и мой :)) автоматически добавляет импорт именно в таком формате

2024-10-31 22:30 UTC, Chamber6821 approved these changes

2024-10-31 22:31 UTC, merged